title: esilva.net
author: Eduardo da Silva
email: emgsilva[at]gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Articles and projects of a Technical Leader, (Sociotechnical) Software Architect, Software Engineer & Continuous Learner.

# social links
twitter_username: emgsilva
github_username: emgsilva
rss: rss
linkedin_username: emgsilva

# disqus configs
disqus:
  shortname: esilva-net

# google analytics configs
google_analytics: UA-114511801-1

# set to true to show excerpts on the homepage
show_excerpts: false

# pages to show on header
header_pages:
  - about.html
  - articles.html 
  - tla_insights.html
  - projects.html
  - talks.html

# Build settings
markdown: kramdown
theme: minima
# exclude:
#   - Gemfile
#   - Gemfile.lock

# shows posts schedule for future release
future: true

# default articles prefix
permalink: /articles/:title

plugins:
  - jekyll-feed